[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Edward Astill", email = "edwardast.ll@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "sympy>=1.14.0",
]

[project.scripts]
typecalc = "typecalc:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
module-name = "typecalc"
