[project]
name = "typecalc-cli"
version = "0.1.0"
description = "CLI for the typecalc engine"
authors = [
    { name = "Edward Astill", email = "edwardast.ll@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "typecalc",
]

[tool.uv.sources]
typecalc = { workspace = true }

[project.scripts]
typecalc = "typecalc_cli.cli:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

